name: Pipeline
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            ./lib
            ./package.json
  publish:
    needs: build
    runs-on: ubuntu-latest
    env:
      CI: true
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          registry-url: https://npm.pkg.github.com/
          scope: '@GenFlowly'
      - uses: actions/download-artifact@v3
        with:
          name: build-artifacts
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.G_TOKEN}}